
from .BehaviouralAnalysis import BehaviouralAnalysis
from .CalculateMethod import CalculateMethod
from .DistributionAnalysis import DistributionAnalysis
from .TimeSeriesAnalysis import TimeSeriesAnalysis